import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './styles/globals.css'

const inter = localFont({
  src: './fonts/InterVariable.woff2',
  variable: '--font-inter-sans',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={` ${inter.variable}`}>{children}</body>
    </html>
  )
}
